add deploy step

diff --git a/.github/workflows/build-and-deploy.yaml b/.github/workflows/build-and-deploy.yaml
--- a/.github/workflows/build-and-deploy.yaml
+++ b/.github/workflows/build-and-deploy.yaml
@@ -10,6 +10,9 @@ on:
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
+  DEPLOY_URL: https://he2.srv.awuerfel.de/deploy
+  IS_DEV: ${{ startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/feature/dockerize')}}
+  
 
 jobs:
   docker-build-and-push:
@@ -28,8 +31,7 @@ jobs:
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
           tags: |
-            type=raw,value=dev,enable=${{ startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/feature/dockerize')}}
-            type=ref,event=tag,enable=true,name=latest
+            type=raw,value=dev,enable=${{ vars.IS_DEV )}}
             type=ref,event=tag,enable=true
           
           labels: |
@@ -51,3 +53,25 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+  deploy:
+    runs-on: self-hosted
+    needs: docker-build-and-push
+    steps:
+      - name: run deployment
+        shell: bash
+        env:
+          DEPLOY_TOKEN_DEV: ${{ secrets.DEPLOY_TOKEN_DEV }}
+          DEPLOY_TOKEN_PROD: ${{ secrets.DEPLOY_TOKEN_PROD }}
+          IS_DEV: ${{ vars.IS_DEV }}
+        run: |
+          DEPLOY_TOKEN=$([ "$IS_DEV" == "true" ] && echo "$DEPLOY_TOKEN_DEV" || echo "$DEPLOY_TOKEN_PROD")
+          curl -sSN -H "Authorization: Bearer $DEPLOY_TOKEN" -X POST "${{ vars.DEPLOY_URL }}" | tee output.txt
+
+          # Check the output file for the string "FAILURE"
+          if grep -q "FAILURE" output.txt; then
+            echo "Deployment failed. FAILURE detected in output."
+            exit 1
+          else
+            echo "Deployment successful."
+          fi
